version: '3.4'

services:

  restaurantservices:
    image: ${DOCKER_REGISTRY-}jonasanne/restaurantservices
    build:
      context: .
      dockerfile: RestaurantServices/Dockerfile


  orderservices:
    image: ${DOCKER_REGISTRY-}jonasanne/orderservices
    build:
      context: .
      dockerfile: OrderServices/Dockerfile


  apigateway:
    image: ${DOCKER_REGISTRY-}jonasanne/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile


  pizzaservices:
    image: ${DOCKER_REGISTRY-}pizzaservices
    build:
      context: .
      dockerfile: PizzaServices/Dockerfile

